language: python
python:
  - '3.6'
install:
  - pip install nose twine
script:
  - ./setup.py build sdist
  - twine check dist/*
  - pip install .
  - nosetests
deploy:
  provider: pypi
  user: pfariello
  password:
    secure: JS+5duiZMSxyk6s4RgaHBTMUSNC3RKtrTPT/JD2k8J9JreWIfRCzGD96c0Q6ENYxN9/PopgSkLRHo7zzErL/s4JO7Wd5j9KfSqvjlMoUyFaPFQjVOSQrXzXC2wYDoJfyxSZy1Kk6Ta9XQ4XIz07cZlWh/8ObCfQzZR1qBUvBFI6ZY/ovIEgHgHYeGwv0N8YYyhm/PvDGrWUs8FCaknSyhG+gyM1aRgtTpxj7Wdoq+j1TLEiUeUxIM6ICkFSOLAv9NKTmXtz+PmdyGhnZaPwQXIFknvyPZ8ZlzyZrXeuP5PhG6F8p4Eaxyb5u7PW73bAiSpg/0uuQtAFD2i+IQeghN+gzAUMFBQprxcgslGY98c95T0SgesMNoGyHPKbuEr22oyCK8VnMzTwMk0PErSHixPV9n0gwqlRcS3iedil0rVyKNwk4dsz5AeQHPKZcXTpz9Ylo3fggkA494wOPomdBlOHWHCXtXOOY4bB9fNdEDYcg742tC30PBHwI4xobhrOSYXPkMPulsm/hIPCmCNsRwQP09aP6b2vK99WCg6ksOnSY09ovPpq245PhtnOG9uJnxWAduC5sQsjUfun0C5B5dCWRnX9VSAykq6mDfoCH6iq0yqa/VsA3tzBpXftQwzgBMKqhMGY0yG6aUxrB+NCbCOrhuVlX2TtwduYBGgc5TmU=
  on:
    tags: true
    python: '3.6'
  skip_existing: true
